version: "3"

services:
  proxy:
    image: "nginx:latest"
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /home/ubuntu/melting/melting-fe/dist:/usr/share/nginx/html
    networks:
      - my_network
    
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: "certbot/certbot"
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  my_network:
    driver: bridge